# ---------------------------------------------------------------------------
# Path-based label configuration for actions/labeler@v5
# Automatically applies labels to PRs based on changed file paths.
# ---------------------------------------------------------------------------

# --- App / Shell ---
scope/shell:
  - changed-files:
      - any-glob-to-any-file: 'apps/web-next/**'

# --- SDK ---
scope/sdk:
  - changed-files:
      - any-glob-to-any-file: 'packages/plugin-sdk/**'

# --- Shared packages (broader) ---
scope/packages:
  - changed-files:
      - any-glob-to-any-file: 'packages/**'

# --- Infrastructure / CI / DevOps ---
scope/infra:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'bin/**'
          - 'docker-compose*'
          - 'vercel.json'

# --- Backend services ---
scope/backend:
  - changed-files:
      - any-glob-to-any-file: 'services/**'

# ---------------------------------------------------------------------------
# Per-plugin labels (one label per plugin directory)
# ---------------------------------------------------------------------------
plugin/capacity-planner:
  - changed-files:
      - any-glob-to-any-file: 'plugins/capacity-planner/**'

plugin/community:
  - changed-files:
      - any-glob-to-any-file: 'plugins/community/**'

plugin/marketplace:
  - changed-files:
      - any-glob-to-any-file: 'plugins/marketplace/**'

plugin/developer-api:
  - changed-files:
      - any-glob-to-any-file: 'plugins/developer-api/**'

plugin/plugin-publisher:
  - changed-files:
      - any-glob-to-any-file: 'plugins/plugin-publisher/**'
