name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    labels:
      - 'type/feature'
  - title: 'Bug Fixes'
    labels:
      - 'type/bug'
  - title: 'Plugins'
    labels:
      - 'plugin/capacity-planner'
      - 'plugin/community'
      - 'plugin/marketplace'
      - 'plugin/developer-api'
      - 'plugin/plugin-publisher'
  - title: 'SDK & Packages'
    labels:
      - 'scope/sdk'
      - 'scope/packages'
  - title: 'Infrastructure'
    labels:
      - 'type/ci'
      - 'scope/infra'
  - title: 'Documentation'
    labels:
      - 'type/docs'
  - title: 'Dependencies'
    labels:
      - 'type/dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'breaking-change'
  minor:
    labels:
      - 'type/feature'
  patch:
    labels:
      - 'type/bug'
      - 'type/refactor'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
