/**
 * Example Plugins API Route
 * GET /api/v1/registry/examples - List example plugins available for publishing
 *
 * Uses a pre-generated examples-manifest.json (created at build time by
 * bin/generate-examples-manifest.cjs) so the route works on Vercel without
 * runtime filesystem access. Falls back to filesystem scanning in local dev
 * if the manifest is missing.
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getAuthToken } from '@/lib/api/response';
import { validateSession } from '@/lib/api/auth';

interface ExampleEntry {
  name: string;
  dirName: string;
  displayName: string;
  description: string;
  category: string;
  author: string;
  version: string;
  icon: string;
  hasBuild: boolean;
  alreadyPublished?: boolean;
}

/**
 * Load example plugin metadata from the pre-generated manifest.
 * On Vercel the manifest is generated during vercel-build.sh.
 * Locally it's generated by start.sh (ensure_plugins_built phase).
 * Falls back to runtime fs scanning when the manifest doesn't exist (dev).
 */
function loadExamples(): ExampleEntry[] {
  // Try the pre-generated manifest first (works on Vercel and local)
  try {
    // require() is statically traceable by @vercel/nft so the JSON
    // file is included in the serverless function bundle automatically.
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const manifest = require('../../../../../../examples-manifest.json');
    if (Array.isArray(manifest) && manifest.length > 0) {
      return manifest;
    }
  } catch {
    // Manifest doesn't exist yet — fall through to fs scanning
  }

  // Fallback: runtime filesystem scanning (local dev only)
  try {
    // Dynamic require so these don't affect Vercel function bundling
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const fs = require('fs');
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const path = require('path');
    // Walk up from Next.js cwd (apps/web-next/) to find monorepo root
    let rootDir = process.cwd();
    for (let i = 0; i < 5; i++) {
      if (fs.existsSync(path.join(rootDir, 'examples'))) break;
      rootDir = path.dirname(rootDir);
    }
    const examplesDir = path.join(rootDir, 'examples');
    if (!fs.existsSync(examplesDir)) return [];

    return fs
      .readdirSync(examplesDir)
      .filter((dir: string) => fs.existsSync(path.join(examplesDir, dir, 'plugin.json')))
      .map((dir: string) => {
        const manifest = JSON.parse(
          fs.readFileSync(path.join(examplesDir, dir, 'plugin.json'), 'utf8'),
        );
        const rawAuthor = manifest.author;
        const authorName = typeof rawAuthor === 'string' ? rawAuthor : rawAuthor?.name;
        return {
          name: dir.replace(/-([a-z])/g, (_: string, c: string) => c.toUpperCase()),
          dirName: dir,
          displayName: manifest.displayName || dir,
          description: manifest.description || '',
          category: manifest.category || 'example',
          author: authorName || 'NAAP Examples',
          version: '1.0.0',
          icon: manifest.frontend?.navigation?.icon || 'Box',
          hasBuild: false,
        };
      })
      .sort((a: ExampleEntry, b: ExampleEntry) => a.displayName.localeCompare(b.displayName));
  } catch {
    return [];
  }
}

export async function GET(request: NextRequest): Promise<NextResponse> {
  try {
    const token = getAuthToken(request);
    if (!token) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const user = await validateSession(token);
    if (!user) {
      return NextResponse.json({ error: 'Invalid or expired session' }, { status: 401 });
    }

    const flag = await prisma.featureFlag.findUnique({
      where: { key: 'enableExamplePublishing' },
    });
    if (!flag?.enabled) {
      return NextResponse.json(
        { error: 'Example plugin publishing is not enabled' },
        { status: 403 },
      );
    }

    const examples = loadExamples();

    const publishedPkgs = examples.length > 0
      ? await prisma.pluginPackage.findMany({
          where: {
            name: { in: examples.map((e) => e.name) },
            publishStatus: 'published',
          },
          select: { name: true },
        })
      : [];
    const publishedSet = new Set(publishedPkgs.map((p) => p.name));

    const result = examples.map((e) => ({
      ...e,
      alreadyPublished: publishedSet.has(e.name),
    }));

    return NextResponse.json({ success: true, examples: result });
  } catch (err) {
    console.error('List examples error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
